import os
from settings import HEALTHY_PLANTS_DIR, INFECTED_PLANTS_DIR
from functions import preprocess_dataset, healthy_plants_directory, infected_plants_directory, processed_healthy_directory, processed_infected_directory

